[package]
name = "mcmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# packet = "0.1.4"
anyhow = "1"
log = "0.4"
permutator = "0.4.3"
